### ISSUE TITLE
fixed-plugin not included in the latest version

### ISSUE THREAD

**Issue by osft** [creativetimofficial/ct-now-ui-dashboard-pro-angular#1]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [ x ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

fixed-plugin component should be included in the latest version.

  │   │   │   ├── fixed-plugin
  │   │   │   │   ├── fixed-plugin.component.css
  │   │   │   │   ├── fixed-plugin.component.html
  │   │   │   │   ├── fixed-plugin.component.spec.ts
  │   │   │   │   └── fixed-plugin.component.ts

# Current Behavior

The readme file and the documentation says that fixed-plugin component is included and it is not

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Today I bought this template and the downloaded file does not include the mentioned component.

**Comment by chelaruc** [comment]
@osft fixed in v1.0.1
