### ISSUE TITLE
[Bug] Submenu not opening on IE11

### ISSUE THREAD

**Issue by Kliton** [creativetimofficial/ct-now-ui-dashboard-pro-angular#2]
### Version
latest
### Steps to reproduce
1. Open side menu
2. Click on a item that have a submenu

### What is expected?
To view submenu
### What is actually happening?
Nothing. Submenu don't open ( in chrome and firefox works )

---

**Comment by chelaruc** [comment]
Hi, @Kliton. Unfortunately, we don't support IE anymore. Best, Ciprian
