### ISSUE TITLE
Color of Switch

### ISSUE THREAD

**Issue by helaquiz** [creativetimofficial/ct-now-ui-dashboard-pro-angular#3]
https://demos.creative-tim.com/now-ui-dashboard-pro-angular/#/documentation/crs

I following of your document but i cant change color of "bSwitch" Component

And 

https://demos.creative-tim.com/now-ui-dashboard-pro-angular/#/forms/extended

on your demo if no color too. 

Need help.

**Comment by chelaruc** [comment]
Hi, @helaquiz! Thank you for using our product. The bSwitch colors are: brown, blue, green, orange, red and default. All the best, Ciprian
